### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by AlaeddineMessadi** [hashicorp/next-mdx-enhanced#120]
Hi everyone,

I want to migrate my blog from using Contentful to `next-mdx-enhanced`.
Right after installing the package, creating the layout and the first mdx page I get this error

```
(node:7978) UnhandledPromiseRejectionWarning: TypeError: this.getOptions is not a function
    at Object.loader (file:///Users/ale/Code/Local/web/myblog-conentful-nextjs/node_modules/@mdx-js/loader/lib/index.js:36:55)
    at /Users/ale/Code/Local/web/myblog-conentful-nextjs/node_modules/@mdx-js/loader/index.cjs:14:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7978) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:7978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I also have this configuration in `next.config.js`
```
module.exports = withPlugins(
	[
		withSourceMap,
		withMdxEnhanced({
			layoutPath: 'layouts',
			defaultLayout: true,
			fileExtensions: ['mdx', 'md'],
			usesSrc: false,

			reExportDataFetching: false
		})
	]
);
```

Versions:

"next": "^10.0.8",
"next-compose-plugins": "^2.2.0",
"@mdx-js/loader": "^2.1.1",
"react": "^17.0.1",
"next-mdx-enhanced": "^5.0.0"

I tried many solutions non worked for me. any ideas? Thank you

**Comment by AlaeddineMessadi** [comment]
After I removed `@mdx-js/loader` from the project, now it works
