### ISSUE TITLE
path concatenation without `/` in Windows

### ISSUE THREAD

**Issue by loganpowell** [hashicorp/next-mdx-enhanced#13]
Hey there!

Got super excited when I found this, but I'm having some issues:

```
Module not found: Can't resolve 'C:UsersloganProjectscensusLUCA-appealslayoutsdocs-page' in 'C:\Users\logan\Projects\census\LUCA-appeals\pages'
```

Might this be an OS issue? Which are you using?

**Comment by jescalan** [comment]
Oh interesting - yes this was developed on a mac. If you run the linux shell on windows it should work without issue. Are there any more details in that error trace? I'd love to patch this still

**Comment by loganpowell** [comment]
sure!
```
[ error ] ./pages/faq.mdx
Module not found: Can't resolve 'C:UsersloganProjectscensusLUCA-appealslayoutsdocs-page' in 'C:\Users\logan\Projects\census\LUCA-appeals\pages'
ModuleNotFoundError: Module not found: Error: Can't resolve 'C:UsersloganProjectscensusLUCA-appealslayoutsdocs-page' in 'C:\Users\logan\Projects\census\LUCA-appeals\pages'
    at factory.create (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\webpack\lib\Compilation.js:821:10)
    at factory (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\webpack\lib\NormalModuleFactory.js:401:22)
    at resolver (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at C:\Users\logan\Projects\census\LUCA-appeals\node_modules\neo-async\async.js:2830:7
    at C:\Users\logan\Projects\census\LUCA-appeals\node_modules\neo-async\async.js:6877:13
    at normalResolver.resolve (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (C:\Users\logan\Projects\census\LUCA-appeals\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
```

**Comment by loganpowell** [comment]
I think the default `layoutsPath` isn't quite working... It seems to set the directory to `layouts` even if I change it to something else

**Comment by jescalan** [comment]
This is really odd, I don't see any spot where it would make sense for this to happen in the source. Can you post the line that's causing it - basically the smallest possible reproduction assuming we have a minimal nextjs setup with this plugin added?

**Comment by JMFURY** [comment]
@loganpowell We looked into the Windows path issues and have opened a pull request here: https://github.com/hashicorp/next-mdx-enhanced/pull/14

**Comment by loganpowell** [comment]
You guys are awesome

**Comment by jescalan** [comment]
We are now running our test suite in CI on both linux and windows containers to prevent any future regression ✨
